export const COUNTER_INCREMENT_REQUEST = 'COUNTER_INCREMENT_REQUEST';
export const COUNTER_INCREMENT_SUCCESS = 'COUNTER_INCREMENT_SUCCESS';
export const COUNTER_INCREMENT_FAILED = 'COUNTER_INCREMENT_FAILED';
